### ISSUE TITLE
Fail to install mongodb driver

### ISSUE THREAD

**Issue by SuperbTUM** [evanugarte/mongocxx-tutorial#8]
Hello, thanks for the hard work! Unfortunately, I encountered the following error with your setup code.

```
CMake Error at src/bsoncxx/CMakeLists.txt:113 (find_package):
  Could not find a configuration file for package "libbson-1.0" that is
  compatible with requested version "1.13.0".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/libbson-1.0/libbson-1.0-config.cmake, version: 1.9.2
```
I am using Ubuntu 18.04 and Visual Studio Code for your information. CMake version 3.25.1
Any suggestion is highly appreciated.

**Comment by evanugarte** [comment]
thanks for bringing this up, looking into this now

**Comment by evanugarte** [comment]
I opened #9 with some changes to the setup script, could you let me know if they work for you?

**Comment by SuperbTUM** [comment]
Hi @evanugarte, it looks like this is neither a version problem nor a make problem on your side, as I always got the same error message. I assume it is because I did not get the proper prerequisite. I read a possible [solution](https://www.mongodb.com/community/forums/t/problems-trying-to-compile-mongocxx/2084/8), especially paying attention to [Ksortakh_Kraxthar](https://www.mongodb.com/community/forums/u/Ksortakh_Kraxthar), but what it proposed still does not work for me. Can you share your environment? Thanks!

**Comment by evanugarte** [comment]
sure my os is

```
Linux <machine name> 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

maybe before running the script try uninstalling the packages that the script installs with
```sh
sudo apt-get update

sudo apt-get remove cmake libmongoc-1.0-0 libbson-1.0 cmake libssl-dev libsasl2-dev zlib1g-dev
```

**Comment by evanugarte** [comment]
any update on this? i wanted to close this issue / merge the above pr
